// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzAea0CM0W9vM35PnxTqrTjfWo4PnX4aY',
    appId: '1:779973149666:web:3681e7ec7d86ed893f6fbb',
    messagingSenderId: '779973149666',
    projectId: 'kazhutha-3f030',
    authDomain: 'kazhutha-3f030.firebaseapp.com',
    storageBucket: 'kazhutha-3f030.firebasestorage.app',
    measurementId: 'G-DXP92F97H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUxSJBbnSbD6lgSXJTzpqHH245LXdojno',
    appId: '1:779973149666:android:fc55cd9d9e69d81b3f6fbb',
    messagingSenderId: '779973149666',
    projectId: 'kazhutha-3f030',
    storageBucket: 'kazhutha-3f030.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVm_22vVVDDP6uZMQ2c1ilmrEnb_TBFt4',
    appId: '1:779973149666:ios:029ab0315097222f3f6fbb',
    messagingSenderId: '779973149666',
    projectId: 'kazhutha-3f030',
    storageBucket: 'kazhutha-3f030.firebasestorage.app',
    iosBundleId: 'com.example.kazhuthaGame',
  );
}
